services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: quantumtrades_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 quantumtrades.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: quantumtrades_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 2002

volumes:
  mysql_data:
