# Generated by Django 5.2.5 on 2025-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_order_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('bought', 'Bought'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
